name: Advanced CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Debug AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID is set to: ${AWS_ACCESS_KEY_ID:-(not visible due to masking)}"
        aws sts get-caller-identity || echo "AWS CLI authentication failed"

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 343218214766.dkr.ecr.us-east-2.amazonaws.com

    - name: Build and Push Docker Image
      run: |
        cd my-app
        docker build -t awsdevops-nginx:latest .
        docker tag awsdevops-nginx:latest 343218214766.dkr.ecr.us-east-2.amazonaws.com/awsdevops-nginx:latest
        docker push 343218214766.dkr.ecr.us-east-2.amazonaws.com/awsdevops-nginx:latest
