# Minimal secrets test - March 08, 2025
name: Secrets Test Pipeline
on: [push]
jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test Secrets
        run: |
          echo "AWS_ACCESS_KEY_ID set: ${{ secrets.AWS_ACCESS_KEY_ID != '' && 'yes' || 'no' }}"
          echo "AWS_SECRET_ACCESS_KEY set: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' && 'yes' || 'no' }}"
          echo "Access Key ID (masked): ${{ secrets.AWS_ACCESS_KEY_ID }}"
